# Generated by Django 2.1 on 2019-10-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=100)),
                ('Image_caption', models.CharField(max_length=200)),
                ('Likes', models.IntegerField(default=0)),
                ('Comments', models.CharField(max_length=300)),
            ],
        ),
    ]
